### ISSUE TITLE
Could you please share me standard LDA (or onlineLD, Gibbs sampling) python code with 20newsgroup dataset?

### ISSUE THREAD

**Issue by teahann** [akashgit/Neural-Variational-Inference-for-Topic-Models#13]
Thanks for sharing this code!
I'm doing my project at school with VAE for LDA, and i have to compare with LDA. Please share me LDA (or onlineLDA, Gibbs sampling) python code with 20newsgroups dataset. Thank you so much.

**Comment by akashgit** [comment]
I used the sklearn version for MEAN FIELD VI and MALLET for Gibbs sampling. Both are freely available to download.
