### ISSUE TITLE
Topic Classification

### ISSUE THREAD

**Issue by lakshmish** [akashgit/Neural-Variational-Inference-for-Topic-Models#2]
Hello Akash,

  thanks very much for sharing this code. Do you also have a class for topic classification given unseen text?

**Comment by akashgit** [comment]
I'm not sure I understand what topic classification means but assuming you're interested in inference of \theta, you can change the test method to additionally output that. 
I'll try to add it to the main code soon.

**Comment by lakshmish** [comment]
Thanks for the reply. Once the model is trained, and using this model how to detect topic of a new sample text? Is it possible to provide some code to identify topic of new sample text. thanks.

**Comment by lakshmish** [comment]
exactly what you were suggesting. :)

**Comment by akashgit** [comment]
i've added `topic_prop` method to the models. This will output the topic proportion vector for each document for a trained model. Apply softmax transformation to the output of this method to infer theta.

**Comment by lakshmish** [comment]
Thanks very much..
