### ISSUE TITLE
How to access topic-word probabilities from trained model?

### ISSUE THREAD

**Issue by michaelchughes** [akashgit/Neural-Variational-Inference-for-Topic-Models#3]
Thanks for sharing your code! I'm wondering how I can access the trained topic-word probabilities.

The partial_fit method defined in nvlda.py produces as output a  2D array from weights_gener['h2'], which looks like the right shape (n_topics x n_vocabs).

If I throw this through a softmax (exp and normalize each row), will I correctly calculate the probability of each word under each topic?

Things look almost right when I do this, but just want to be sure I'm on the right track. Thanks.

**Comment by akashgit** [comment]
That's correct. I additionally sort them while showing the topics.
