### ISSUE TITLE
How to get the average topic coherence?

### ISSUE THREAD

**Issue by hilda92** [akashgit/Neural-Variational-Inference-for-Topic-Models#4]
Hello, Akash ! Thanks for sharing the code!!! 
I have some problem about the average topic coherence.
In paper, the average topic coherence is NPMI between all the pairs of words in a set of topics. If all the pairs of words in a set of topics means the top n words of each topic of beta? If beta is K*V, NPMI=sum( NPMI(x,y),x y is top n words of each topic of beta) ) / K ?
Can you share the code about the computing average topic coherence?
Help wanted! Thank you!

**Comment by akashgit** [comment]
Hi, the topic coherence code is avaliable from the original author's of that paper. Also you can look up https://github.com/hyqneuron/pytorch-avitm . @hyqneuron has his own implementation for a pytorch version of AVITM.

**Comment by nzw0301** [comment]
Maybe unrelated my comment, I also release my notebook for a Keras version of your prodLDA model. I'm happy if someone uses my code.
https://github.com/nzw0301/keras-examples/blob/master/prodLDA.ipynb

**Comment by akashgit** [comment]
Thanks @nzw0301 
If you don't mind I'd like to link your notebook on the project's readme?

**Comment by nzw0301** [comment]
@akashgit Of course!
