### ISSUE TITLE
TF 1.0 support and small numpy casting issue

### ISSUE THREAD

**Issue by govg** [akashgit/Neural-Variational-Inference-for-Topic-Models#5]
Hi, 

Thanks for releasing your code. I just had two quick notes

- The function tf.mul is deprecated in favor of tf.multiply. Are you working with the earlier version of TF, by any chance? If so, I will ignore this

- I get an error that a float object can't be interpreted as an index. It arises from line 36 in the nvlda.py file, where you initialize with np.ones((1,float)) instead of ((1,int)). I have changed this, and it seems to work after that. 

Thanks and regards,
Govind

**Comment by akashgit** [comment]
Thanks Govind, yes I need to update the code for TF 1 (higher) atm it is needs the older version. Feel free to reopen if needed.
