### ISSUE TITLE
How do you get the train.txt.npy data?

### ISSUE THREAD

**Issue by honghongyier** [akashgit/Neural-Variational-Inference-for-Topic-Models#6]
I have get the vocab.pkl, but I can't understand the numbers in train.txt.npy's meaning. Please help me, thank you!

**Comment by akashgit** [comment]
From your description I am not sure what exactly is that you are asking for. Each document is encoded as bag-of-words, i.e. how many times each of the words (from the vocabulary) occur in a document.

**Comment by honghongyier** [comment]
Thank you very much. I get it. Thanks for your sharing of these codes, from which I have learnt a lot.
